export const SAVE_USER_NAME = "SAVE_USER_NAME";
export const SKIP_INTRO = "SKIP_INTRO";
export const CHANGE_NAME = "CHANGE_NAME";

export const START_SPINNING = "START_SPINNING";
export const START_REVOLVING = "START_REVOLVING";
export const START_SIGHTSEEING = "START_SIGHTSEEING";

export const PICK_COORDINATES = "PICK_COORDINATES";

export const NO_NEARBY_CITIES = "NO_NEARBY_CITIES";
export const NEARBY_CITIES_FETCH_SUCCEEDED = "NEARBY_CITIES_FETCH_SUCCEEDED";
export const NEARBY_CITIES_FETCH_FAILED = "NEARBY_CITIES_FETCH_FAILED";

export const GET_SINGLE_CITY_DATA = "GET_SINGLE_CITY_DATA";
export const SINGLE_CITY_DATA_FETCH_SUCCEEDED =
  "SINGLE_CITY_DATA_FETCH_SUCCEEDED";
export const SINGLE_CITY_DATA_FETCH_FAILED = "SINGLE_CITY_DATA_FETCH_FAILED";
export const RESET_SINGLE_CITY = "RESET_SINGLE_CITY";
export const EXTENDED_CITY_DATA_FETCH_SUCCEDEED =
  "EXTENDED_CITY_DATA_FETCH_SUCCEDEED";
export const EXTENDED_CITY_DATA_FETCH_FAILED =
  "EXTENDED_CITY_DATA_FETCH_FAILED";
